#!/bin/bash
set -e

# MCP Memory Service - Docker Build Script
# Builds the optimized Docker image with pre-downloaded embeddings

echo "=========================================="
echo "MCP Memory Service - Docker Build"
echo "=========================================="
echo ""

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Error: Docker is not installed"
    echo "   Please install Docker Desktop from: https://www.docker.com/products/docker-desktop"
    exit 1
fi

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo "❌ Error: Docker is not running"
    echo "   Please start Docker Desktop and try again"
    exit 1
fi

# Clone or update source repository
REPO_URL="https://github.com/doobidoo/mcp-memory-service"
SOURCE_DIR="./mcp-memory-service"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "📦 Cloning mcp-memory-service repository..."
    echo "   Repository: $REPO_URL"
    if git clone "$REPO_URL" "$SOURCE_DIR"; then
        echo "✅ Repository cloned successfully"
    else
        echo "❌ Error: Failed to clone repository"
        echo "   Check your internet connection and repository access"
        exit 1
    fi
else
    echo "📂 Source directory exists: $SOURCE_DIR"
    read -p "Update repository to latest version? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🔄 Updating repository..."
        cd "$SOURCE_DIR"
        if git pull; then
            echo "✅ Repository updated successfully"
        else
            echo "⚠️  Warning: Failed to update repository, using existing version"
        fi
        cd ..
    fi
fi

# Generate manifest with version information
echo "📝 Generating manifest..."
cd "$SOURCE_DIR"
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=iso 2>/dev/null || echo "unknown")
GIT_COMMIT_MSG=$(git log -1 --format=%s 2>/dev/null || echo "unknown")
cd ..

MANIFEST_FILE="manifest.json"
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$MANIFEST_FILE" << EOF
{
  "repository": {
    "url": "$REPO_URL",
    "commit": "$GIT_COMMIT",
    "commit_short": "$GIT_COMMIT_SHORT",
    "branch": "$GIT_BRANCH",
    "commit_date": "$GIT_COMMIT_DATE",
    "commit_message": "$GIT_COMMIT_MSG"
  },
  "build": {
    "date": "$BUILD_DATE",
    "script_version": "1.0"
  }
}
EOF

echo "✅ Manifest created: $MANIFEST_FILE"
echo ""
echo "Repository Version:"
echo "  Branch:  $GIT_BRANCH"
echo "  Commit:  $GIT_COMMIT_SHORT"
echo "  Date:    $GIT_COMMIT_DATE"
echo "  Message: $GIT_COMMIT_MSG"
echo ""

echo "✅ Docker is running"
echo "✅ Source directory ready: $SOURCE_DIR"
echo ""

# Configure data directory
CONFIG_FILE="config.sh"
if [ -f "$CONFIG_FILE" ]; then
    # Load existing configuration
    source "$CONFIG_FILE"
    DEFAULT_DATA_DIR="${MCP_DATA_DIR:-./data}"
else
    DEFAULT_DATA_DIR="./data"
fi

echo "=========================================="
echo "Data Storage Configuration"
echo "=========================================="
echo ""
echo "Where would you like to store the SQLite database?"
echo "This directory will contain:"
echo "  - sqlite_vec.db (the vector database)"
echo "  - backups/ (database backups)"
echo ""
echo "Default: $DEFAULT_DATA_DIR"
read -p "Enter path (or press Enter for default): " DATA_DIR_INPUT

# Use default if no input provided
if [ -z "$DATA_DIR_INPUT" ]; then
    DATA_DIR="$DEFAULT_DATA_DIR"
else
    DATA_DIR="$DATA_DIR_INPUT"
fi

# Expand ~ to home directory if present
DATA_DIR="${DATA_DIR/#\~/$HOME}"

# Convert to absolute path if relative
if [[ "$DATA_DIR" != /* ]]; then
    DATA_DIR="$(pwd)/$DATA_DIR"
fi

echo ""
echo "📁 Data directory: $DATA_DIR"

# Create data directory if it doesn't exist
if [ ! -d "$DATA_DIR" ]; then
    echo "   Creating directory..."
    if mkdir -p "$DATA_DIR"; then
        echo "✅ Data directory created"
    else
        echo "❌ Error: Failed to create data directory"
        exit 1
    fi
else
    echo "✅ Data directory exists"
fi

# Save configuration
cat > "$CONFIG_FILE" << EOF
# MCP Memory Service Configuration
# Auto-generated by build.sh
MCP_DATA_DIR="$DATA_DIR"
EOF
echo "✅ Configuration saved to $CONFIG_FILE"
echo ""

# Export for docker-compose
export MCP_DATA_DIR="$DATA_DIR"

# Parse arguments
NO_CACHE=""
QUIET=""
PROGRESS="auto"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-cache)
            NO_CACHE="--no-cache"
            echo "🔄 Building with --no-cache (fresh build)"
            shift
            ;;
        --quiet)
            QUIET="--quiet"
            PROGRESS="quiet"
            shift
            ;;
        --verbose)
            PROGRESS="plain"
            shift
            ;;
        -h|--help)
            echo "Usage: ./build.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --no-cache    Build from scratch (ignores cache)"
            echo "  --quiet       Minimal output"
            echo "  --verbose     Detailed build output"
            echo "  -h, --help    Show this help message"
            echo ""
            echo "Examples:"
            echo "  ./build.sh                  # Normal build"
            echo "  ./build.sh --no-cache       # Fresh build"
            echo "  ./build.sh --verbose        # Detailed output"
            exit 0
            ;;
        *)
            echo "❌ Unknown option: $1"
            echo "   Use --help to see available options"
            exit 1
            ;;
    esac
done

echo "Build Configuration:"
echo "  - Base Image: python:3.12-slim"
echo "  - PyTorch: CPU-only (saves ~2GB)"
echo "  - Embedding Model: all-MiniLM-L6-v2 (pre-downloaded)"
echo "  - Expected Size: ~1.5-2GB"
echo "  - Build Time: 3-5 minutes"
echo ""

read -p "Start build? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Build cancelled"
    exit 0
fi

echo ""
echo "🔨 Building Docker image..."
echo "   This may take 3-5 minutes..."
echo ""

# Build the image
START_TIME=$(date +%s)

if docker-compose build $NO_CACHE $QUIET --progress=$PROGRESS; then
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    MINUTES=$((DURATION / 60))
    SECONDS=$((DURATION % 60))

    echo ""
    echo "=========================================="
    echo "✅ Build completed successfully!"
    echo "=========================================="
    echo ""
    echo "Build Statistics:"
    echo "  - Duration: ${MINUTES}m ${SECONDS}s"

    # Get image size
    IMAGE_SIZE=$(docker images mcp-memory-service --format "{{.Size}}" | head -n 1)
    if [ -n "$IMAGE_SIZE" ]; then
        echo "  - Image Size: $IMAGE_SIZE"
    fi

    echo ""
    echo "Repository Version:"
    echo "  - Commit: $GIT_COMMIT_SHORT ($GIT_BRANCH)"
    echo "  - Date:   $(echo $GIT_COMMIT_DATE | cut -d' ' -f1)"
    echo "  - Build:  $BUILD_DATE"
    echo "  - Manifest: manifest.json"

    echo ""
    echo "Next Steps:"
    echo "  1. Start the service:    ./run.sh start"
    echo "  2. View logs:            ./run.sh logs"
    echo "  3. Check status:         ./run.sh status"
    echo "  4. Access dashboard:     http://localhost:8000/"
    echo ""
    echo "Data Storage:"
    echo "  Database location:       $DATA_DIR/sqlite_vec.db"
    echo "  Backups location:        $DATA_DIR/backups/"
    echo ""
    echo "Claude Code Configuration:"
    echo "  Add to ~/.claude/settings.json:"
    echo '  {
    "mcpServers": {
      "memory": {
        "type": "http",
        "url": "http://localhost:8000/mcp"
      }
    }
  }'
    echo ""
else
    echo ""
    echo "❌ Build failed"
    echo ""
    echo "Troubleshooting:"
    echo "  - Check Docker Desktop is running"
    echo "  - Ensure enough disk space (need ~3GB)"
    echo "  - Try: ./build.sh --no-cache"
    echo "  - Check logs above for specific errors"
    exit 1
fi
